<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Jumoo.TranslationManager.UmbracoAi</PackageId>
		<Product>Jumoo.TranslationManager.UmbracoAi</Product>
		<Title>Jumoo.TranslationManager.UmbracoAi</Title>
	</PropertyGroup>

	<PropertyGroup>
		<PackageTags>umbraco, umbraco-cms, umbraco-ai, translations, umbraco-marketplace</PackageTags>
		<Description>UmbracoAi Connector for Jumoo.TranslationManager</Description>

		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Jumoo.TranslationManager.AI" Version="17.4.1" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="17.6.2" />
		<PackageReference Include="Umbraco.Cms.Web.Common" Version="17.6.2" />
		<PackageReference Include="Umbraco.Cms.Api.Common" Version="17.6.2" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="17.6.2" />
		<PackageReference Include="Umbraco.AI.Core" Version="17.3.1" />
	</ItemGroup>

	<ItemGroup>
		<!-- Dont include the client folder as part of packaging nuget build -->
		<Content Remove="Client\**" />

		<!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
